project:
  type: website

website:
  title: "DSAN-5000"
  sidebar:
    style: floating
    search: true
    left:

      - text: "Introduction"
        file: index.qmd

      - text: "Home"
        file: ../about.qmd

      - text: "Code"
        file: https://github.com/anly501/dsan-5000-project-isfarbaset

      - text: "Data"
        file: https://github.com/anly501/dsan-5000-project-isfarbaset

      - text: "Data Gathering"
        file: ./data/00-raw-data

      - text: "Data Cleaning"
        file: ./data/01-modified-data

      - text: "Data Exploration"
        file: eda/eda.ipynb

      - text: "Clustering"
        file: clustering/clustering.qmd

      - text: "Dimensionality Reduction"
        file: ""

      - text: "Decision Trees"
        file: ""
      
      - text: CLassification
        file: ""
          
      - text: Regression
        file: ""

      - text: "ARM"
        file: ""

      - text: "Conclusions"
        file: ""
format:
  html:
    theme: cosmo
    toc: true