project:
  type: website

website:
  title: "Isfar Baset"
  sidebar:
    style: "floating"
    title: "Projects"
    search: true
    contents:
      - section: "DSAN 5000"
        contents:
          
        - href: 5000-website/index.qmd
          text: Introduction

      - section: "DSAN 5100"
        contents:
        - href: 5100-website/index.qmd
          text: Introduction
  

      - section: "DSAN 6300"
        contents:
          - href: 6300-website/index.qmd
            text: Introduction

format:
  html:
    theme: cosmo
    toc: true