project:
  type: website

website:
  title: Isfar Baset
  navbar:
    background: primary
    search: true
    left:
      # - text: "Home"
      #   file: index.qmd
      # - text: "Tutorials"
      #   file: tutorials.qmd
      - text: "DSAN 5000"
        file: 5000-website/index.qmd
      # - text: "Fundamentals"
      #   file: fundamentals.qmd
      # - text: "Reference"
      #   file: reference.qmd

  sidebar:
    # - title: "Tutorials"
    #   style: "docked"
    #   background: light
    #   contents:
    #     - tutorials.qmd
    #     - tutorial-1.qmd
    #     - tutorial-2.qmd

    - title: "DSAN 5000"
      contents:
        - text: Introduction
          file: 5000-website/index.qmd
        # navigation items
        # - text: Introduction
        #   file: 5000-website/index.qmd
        - text: Code
          href: https://github.com/anly501/dsan-5000-project-isfarbaset
        
        - text: Data
          contents: 
            # - text: Github Repo
            text: Code
            href: https://github.com/anly501/dsan-5000-project-isfarbaset
            # - text: Modified Data
            #   file: ../../data/01-modified-data/example.csv

        - text: Data Gathering
          contents:
            - text: Initial Data Gathering
              file: 5000-website/eda/data_gathering.ipynb

            - text: Additional Data Gathering
              file: 5000-website/eda/data_gathering-extra.ipynb

        - text: Data Cleaning
          file: 5000-website/eda/data_cleaning.ipynb

        - text: Data Exploration
          file: 5000-website/eda/eda.ipynb

        - text: Naïve Bayes
          file: 5000-website/eda/naive_bayes.ipynb

        - text: Clustering
          file: 5000-website/clustering/clustering.ipynb

        - text: Dimensionality Reduction
          file: 5000-website/dim-reduction/dim-reduction.ipynb

        - text: Decision Trees
          contents: 
            - text: Classification
            - text: Regression
        - text: ARM
        - text: Conclusions

    - title: "Fundamentals"
      contents:
        - fundamentals.qmd
        # navigation items

    - title: "Reference"
      contents:
        - reference.qmd
        # navigation items
    
format:
  html:
    theme: cosmo
    toc: true


